name: RSYNC Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    # Install SSH Key
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2.2.0
      with:
        # SSH private key
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        # public keys of SSH servers
        known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: |
        cd ${{ github.workspace }}/Radial/
        dotnet publish --runtime linux-x64 --configuration Release --output ${{ github.workspace }}/publish/ --self-contained false -p:ExcludeApp_Data=true
        rm -R ${{ github.workspace }}/publish/App_Data/
        rsync -r -v ${{ github.workspace }}/publish/ ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOSTNAME }}:/var/www/${{ secrets.APP_NAME }}/
        ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOSTNAME }} systemctl restart ${{ secrets.APP_NAME }}
